In [1]:
import numpy as np
a = np.array([1,2,3,4])
x=a*2
print(x)

[2 4 6 8]


In [2]:
np.zeros(3)

array([0., 0., 0.])

In [3]:
a=['H','e','l','l','o','!']
a

['H', 'e', 'l', 'l', 'o', '!']

In [4]:
a[0:5]

['H', 'e', 'l', 'l', 'o']

In [45]:
a[-1]

'k'

In [ ]:
#nlkt.punkt

In [ ]:
a

In [24]:
a="NumPy, short for Numerical Python, is one of the.most important foundational pack"
a

'NumPy, short for Numerical Python, is one of the.most important foundational pack'

In [4]:
a[0]

'NumPy, short for Numerical Python, is one of the most important foundational pack'

In [44]:
w=a.split("." ",")
y=np.array(w)
y

array(['NumPy, short for Numerical Python, is one of the.most important foundational pack'],
      dtype='<U81')

In [3]:
import nltk
tokenizer = nltk.tokenize.punkt.PunktSentenceTokenizer()
#txt = """ This is one sentence. This is another sentence."""
tokenizer.tokenize(txt)


['SCIENTISTS HAVE LEARNED ?',
 'TO SUPPLEMENT THE SENSE OF SIGHT IN NUMEROUS WAYS.',
 'In front of the tiny pupil of the eye they put, on Mount Palomar, a great monocle 200 inches in diameter, and with it see 2000 times farther into the depths of space.',
 'Or they look through a small pair of lenses arranged as a microscope into a drop of water or blood, and magnify by as much as 2000 diameters the living creatures there, many of which are among man’s most dangerous enemies.',
 'Or, if we want to see distant happenings on earth, they use some of the previously wasted electromagnetic waves to carry television images which they re-create as light by whipping tiny crystals on a screen with electrons in a vacuum.',
 'Or they can bring happenings of long ago and far away as colored motion pictures, by arranging silver atoms and color-absorbing molecules to force light waves into the patterns of original reality.',
 'Or if we want to see into the center of a steel casting or the chest of an

In [2]:
txt="""SCIENTISTS HAVE LEARNED ? TO SUPPLEMENT THE SENSE OF SIGHT IN NUMEROUS WAYS. In front of the tiny pupil of the eye they put, on Mount Palomar, a great monocle 200 inches in diameter, and with it see 2000 times farther into the depths of space. Or they look through a small pair of lenses arranged as a microscope into a drop of water or blood, and magnify by as much as 2000 diameters the living creatures there, many of which are among man’s most dangerous enemies. Or, if we want to see distant happenings on earth, they use some of the previously wasted electromagnetic waves to carry television images which they re-create as light by whipping tiny crystals on a screen with electrons in a vacuum. Or they can bring happenings of long ago and far away as colored motion pictures, by arranging silver atoms and color-absorbing molecules to force light waves into the patterns of original reality. Or if we want to see into the center of a steel casting or the chest of an injured child, they send the information on a beam of penetrating short-wave X rays, and then convert it back into images we can see on a screen or photograph. THUS ALMOST EVERY TYPE OF ELECTROMAGNETIC RADIATION YET DISCOVERED HAS BEEN USED TO EXTEND OUR SENSE OF SIGHT IN SOME WAY."""

In [59]:
print(len.txt)

AttributeError: 'builtin_function_or_method' object has no attribute 'txt'

In [20]:
r=np.array([[1,2,3],[4,5,6]])
r2=np.array([1,2,3])
r3=r*r2
print(r3)

[[ 1  4  9]
 [ 4 10 18]]


In [12]:
y[4]

'Python,'

In [60]:
a=np.size(txt)

In [61]:
a

1

In [62]:
salary=np.array([0,1,0,45453,2324324])
np.where(salary<=0,25000,salary)

array([  25000,       1,   25000,   45453, 2324324])

In [63]:
arrr = np.array([2,4,5,7,45,6,4,6,67,4,45,45])
print(np.sum(arrr))

240


In [64]:
print(np.any(arrr))

True


In [65]:
print(np.all(arrr))

True


In [72]:
np.savez('array.npz',a=arrr)
arrq=np.load('array.npz')
print(arrr[8])

67
