In [4]:
import numpy as np
a= np.array([10,20,30,40,50])

In [3]:
# 2d array   3 x 3
b=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [6]:
# 3d array   3 x 3 x 3 
c=np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,8,9]],
])


In [11]:
#arrange
a=np.arange(10,20)
b=np.arange(10,20,2)
print(a,b)

[10 11 12 13 14 15 16 17 18 19] [10 12 14 16 18]


In [12]:
#zeros
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
b=np.zeros((3,3), dtype=np.int16)
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [14]:
#ones
c=np.ones((4,5))
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
2


In [17]:
print(a.size)
print(b.size)

10
9


In [8]:
e = np.empty((3,3) )
e

array([[3.06e-322, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 3.44e-321],
       [0.00e+000, 0.00e+000, 0.00e+000]])

In [10]:
print(e)

[[3.06e-322 0.00e+000 0.00e+000]
 [0.00e+000 0.00e+000 3.44e-321]
 [0.00e+000 0.00e+000 0.00e+000]]


In [11]:
e.shape


(3, 3)

In [15]:
e.reshape(9)
e

array([[3.06e-322, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 3.44e-321],
       [0.00e+000, 0.00e+000, 0.00e+000]])